### ISSUE TITLE
有无升1.16及fabric版本的想法呢

### ISSUE THREAD

**Issue by taooceros** [reserveword/IMBlocker#1]
1.16.1版已发布，还没有测试过，代码没改，应该不会有问题吧（）
fabric还没接触过（）

**Comment by reserveword** [comment]
@taooceros 啊这，本来想回复的，不小心把你的issue文本编辑了，你知道怎么改回来吗（）
1.16.1版已发布，还没有测试过，代码没改，应该不会有问题吧（）
fabric还没接触过（）

**Comment by taooceros** [comment]
啊这哈哈哈哈哈没事
主要我在用fabric，但又很想用这个mod

**Comment by mrjesen** [comment]
讲真的，高版本用fabric的比forge多很多，强烈建议您更换为fabric核心并支持1.16.1. 
@reserveword

**Comment by reserveword** [comment]
> 
> 
> 讲真的，高版本用fabric的比forge多很多，强烈建议您更换为fabric核心并支持1.16.1.
> @reserveword

主要是因为没接触过fabric，等我学会fabric肯定会支持的（）

**Comment by TUsama** [comment]
然而：https://www.mcbbs.net/forum.php?mod=viewthread&tid=1090731&extra=page%3D1%26filter%3Dauthor%26orderby%3Ddateline

**Comment by mrjesen** [comment]
> 然而：https://www.mcbbs.net/forum.php?mod=viewthread&tid=1090731&extra=page%3D1%26filter%3Dauthor%26orderby%3Ddateline

额。。这个是我写的，我实在是等不起了，只能自己亲自动手了。
