### ISSUE TITLE
非预期的禁用问题

### ISSUE THREAD

**Issue by NightSharp** [reserveword/IMBlocker#11]
1. 在未进入 单人游戏 之前，`模组菜单(包含 Configured 中的配置项编辑)`中的文本输入框是能正常输入中文的
但在进入游戏后，这些输入框就无法再输入中文了。即使再返回开始界面也无济于事
2. 包括一些原本可以输入中文的设置项文本框在内都是这样
3. JourneyMap 编辑路标点名称时也无法正常输入中文
4. 我的版本是 MC-1.18.2-Forge-40.0.32
5. 可能涉及到的模组有
- `InvMove`(用来在打开各种screen时能够继续按方向键移动)
- `Catalogue`(重新设计了模组列表界面)
- `Configured`(可以在游戏内直接对部分模组的配置文件进行编辑)
6. 如有需要我将按需补充

**Comment by reserveword** [comment]
InvMove这个mod从名字上来看就很容易冲突嘛
总之我会先看看他怎么设计的

**Comment by reserveword** [comment]
把debug.log传上来吧
另外你用的mod是什么版本？在删掉本mod之后是可以正常输入中文的吗？

**Comment by NightSharp** [comment]
- 只有部分画面无法输入中文
- 另外白名单黑名单啥的好像没用，我之前把告示牌的规则删掉后仍然可以在告示牌界面输入中文
- 版本是`1.18.1-3.0`，我在MC-`1.18.1`和`1.18.2`上都试过，情况一样。
- 另外还有个小情况，就是无法长按BackSpace进行连续删除

测试的时候忘了测试一种情况，所以分成了两次
1. 第一次
[debug.log.gz](https://github.com/reserveword/IMBlocker/files/8371676/debug.log.gz)

2. 第二次
[debug.log.gz](https://github.com/reserveword/IMBlocker/files/8371743/debug.log.gz)

**Comment by reserveword** [comment]
> 
>     * 另外白名单黑名单啥的好像没用，我之前把告示牌的规则删掉后仍然可以在告示牌界面输入中文
> 

如果是在游戏内改的设置的话，那是因为我只在初始化的时候读取设置，之后就没读取了

>
>     * 还有就是，如果进游戏时没有切换为中文输入法的话，进游戏主界面后再切换就直接在配置界面啥的被禁用了
>

禁用输入法的时候应该没法切换输入法，你在启用输入法的时候切换可能就好了？

**Comment by reserveword** [comment]
在第一个log文件当中，我看到你启动游戏之后
* 在世界选择界面点了一下文本框（这时候应该启用了输入法）
* 然后进入存档
* 打开了物品栏但是没点击文本框
* 关闭物品栏之后又打开了创造物品栏
* 同时激活了jei和创造物品栏的文本框（这时候也应该启用了输入法）
* 最后关闭游戏

在第二个log文件当中，我看到你启动游戏之后
* 去了设置界面（这里设置界面的文本框是没检测到吗？）
* 在标题界面激活了文本框，然后马上切换到世界选择界面（可能是卡了一下有延迟）（这时候应该启用了输入法）
* 然后进入存档
* 在游戏里打开了设置界面（这里设置界面的文本框是没检测到吗？）
* 又进了另一个设置界面
* 又打开了创造物品栏，但是没有激活文本框
* 又用几种方式进入了设置页面，还退出存档了
* 又（在存档外）进入了按键绑定页面，这次激活了文本框

从log推断的话应该是设置界面的文本框没检测到。

**Comment by NightSharp** [comment]
> > ```
> > * 另外白名单黑名单啥的好像没用，我之前把告示牌的规则删掉后仍然可以在告示牌界面输入中文
> > ```
> 
> 如果是在游戏内改的设置的话，那是因为我只在初始化的时候读取设置，之后就没读取了
> 
> > ```
> > * 还有就是，如果进游戏时没有切换为中文输入法的话，进游戏主界面后再切换就直接在配置界面啥的被禁用了
> > ```
> 
> 禁用输入法的时候应该没法切换输入法，你在启用输入法的时候切换可能就好了？

好像是只要启动后游戏窗口失焦后就会直接禁用
另外我在查看debug.log时发现有几次screen检测到null后就把im给禁用了，会不会是这个导致的

**Comment by reserveword** [comment]
>
> 好像是只要启动后游戏窗口失焦后就会直接禁用 另外我在查看`debug.log`时发现有几次`screen`检测到`null`后就把`im`给禁用了，会不会是这个导致的
>

* `screen`就是能挡住游戏画面的gui，像聊天、物品栏、编辑告示牌之类的都是screen
* `null`就是空的意思，`screen`为`null`的意思就是你正在游戏里走来走去，这时候*肯定不能*打字
* 文本框的白名单其实没啥用，只是为了三缺一不好才放上去的，即使放上白名单了也要检测tick和激活状态
* `screen`的白名单应该是有用的，你改完设置重启一下试试呢？

* 游戏窗口失焦这点我好像确实没考虑到，下个版本应该能修复

**Comment by NightSharp** [comment]
> 

- 我是说一些不打算被禁用的Screen和InputBox在失焦后也会被禁用，这时即使反复切换输入法也没用
- 我是在关闭游戏的情况下改的screen白名单，启动后仍然没用

**Comment by reserveword** [comment]
> 
>     * 我是说一些不打算被禁用的Screen和InputBox在失焦后也会被禁用，这时即使反复切换输入法也没用
> 

这是说有些文本框在不激活的时候也要开启输入法吗？

>
>     * 我是在关闭游戏的情况下改的screen白名单，启动后仍然没用
>

启动后log里的白名单有没有对应的条目？

**Comment by reserveword** [comment]
现在看来主要的问题应该是这几个设置mod和journeymap没有实现文本框。考虑到设置mod大部分情况下只需要输入英文，我觉得不用特意兼容这些mod，有需要的可以自己添加对应的screen。对于screen白名单失效的问题我会在确认后修复。

**Comment by NightSharp** [comment]
> > ```
> > * 我是说一些不打算被禁用的Screen和InputBox在失焦后也会被禁用，这时即使反复切换输入法也没用
> > ```
> 
> 这是说有些文本框在不激活的时候也要开启输入法吗？
> 
> > ```
> > * 我是在关闭游戏的情况下改的screen白名单，启动后仍然没用
> > ```
> 
> 启动后log里的白名单有没有对应的条目？

白名单里没有，明明我都加进去了

**Comment by NightSharp** [comment]
> 我有想法了，可能是在mod加载早期其他mod的类还没加载出来？

我看log里面确实是在加载白名单后才开始加载一堆模组，之前只是建立了一个模组列表

**Comment by reserveword** [comment]
更新：动态更新配置的功能已添加，记录遇到的screen的功能已添加，但是需要手动在配置里开启

PS：测试的时候发现一个问题，就是游戏刚开始的时候第一次禁用输入法会失败（log显示我确实触发了禁用输入法的代码），所以一开始虽然没有文本框但输入法是开着的。这个现象在第一次激活一个文本框后就消失了（因为存档选择页面会直接激活文本框所以在这里就消失了）。我修改的时候添加了一个screen改变时同步状态的功能，虽然没彻底解决但也不影响使用了。

**Comment by NightSharp** [comment]
> 更新：动态更新配置的功能已添加，记录遇到的screen的功能已添加，但是需要手动在配置里开启
> 
> PS：测试的时候发现一个问题，就是游戏刚开始的时候第一次禁用输入法会失败（log显示我确实触发了禁用输入法的代码），所以一开始虽然没有文本框但输入法是开着的。这个现象在第一次激活一个文本框后就消失了（因为存档选择页面会直接激活文本框所以在这里就消失了）。我修改的时候添加了一个screen改变时同步状态的功能，虽然没彻底解决但也不影响使用了。

大佬，这个新版本好像还没同步到CurseForge啊，虽然可以直接在GitHub下载

**Comment by NightSharp** [comment]
> 更新：动态更新配置的功能已添加，记录遇到的screen的功能已添加，但是需要手动在配置里开启
> 
> PS：测试的时候发现一个问题，就是游戏刚开始的时候第一次禁用输入法会失败（log显示我确实触发了禁用输入法的代码），所以一开始虽然没有文本框但输入法是开着的。这个现象在第一次激活一个文本框后就消失了（因为存档选择页面会直接激活文本框所以在这里就消失了）。我修改的时候添加了一个screen改变时同步状态的功能，虽然没彻底解决但也不影响使用了。

另外关于配置项的文本表述，我有个小建议，就是名称简短一些，把具体的用途放到对应项的 tooltip 里面，不然配置界面的文本会显示不全

**Comment by NightSharp** [comment]
> 更新：动态更新配置的功能已添加，记录遇到的screen的功能已添加，但是需要手动在配置里开启
> 
> PS：测试的时候发现一个问题，就是游戏刚开始的时候第一次禁用输入法会失败（log显示我确实触发了禁用输入法的代码），所以一开始虽然没有文本框但输入法是开着的。这个现象在第一次激活一个文本框后就消失了（因为存档选择页面会直接激活文本框所以在这里就消失了）。我修改的时候添加了一个screen改变时同步状态的功能，虽然没彻底解决但也不影响使用了。

大佬，我使用时又发现了问题
像第三方模组中的 Screen
你在记录时都会带上模组名称，比如这样
`cloth_config:me.shedaniel.clothconfig2.gui.ClothConfigScreen`
但用这种格式直接加到白名单里的话并不会生效，需要把`:`前的部分删掉后加进去才有效

**Comment by reserveword** [comment]
> 
> 大佬，这个新版本好像还没同步到CurseForge啊，虽然可以直接在GitHub下载

curseforge懒得传那么频繁了，等相对稳定的时候再传吧（其实就是忘了）


> 
> 另外关于配置项的文本表述，我有个小建议，就是名称简短一些，把具体的用途放到对应项的 tooltip 里面，不然配置界面的文本会显示不全
>

我找找看tooltip怎么设置吧

> 
> 大佬，我使用时又发现了问题 像第三方模组中的 Screen 你在记录时都会带上模组名称，比如这样 `cloth_config:me.shedaniel.clothconfig2.gui.ClothConfigScreen` 但用这种格式直接加到白名单里的话并不会生效，还会被直接删掉。 需要把`:`前的部分删掉后加进去才有效
>

确实，这方面怎么说明比较好呢，我感觉挺麻烦的，你有好主意吗
要不我直接兼容两种格式吧，读取配置文件的时候自动删除modid

**Comment by NightSharp** [comment]
> > 大佬，这个新版本好像还没同步到CurseForge啊，虽然可以直接在GitHub下载
> 
> curseforge懒得传那么频繁了，等相对稳定的时候再传吧（其实就是忘了）
> 
> > 另外关于配置项的文本表述，我有个小建议，就是名称简短一些，把具体的用途放到对应项的 tooltip 里面，不然配置界面的文本会显示不全
> 
> 我找找看tooltip怎么设置吧
> 
> > 大佬，我使用时又发现了问题 像第三方模组中的 Screen 你在记录时都会带上模组名称，比如这样 `cloth_config:me.shedaniel.clothconfig2.gui.ClothConfigScreen` 但用这种格式直接加到白名单里的话并不会生效，还会被直接删掉。 需要把`:`前的部分删掉后加进去才有效
> 
> 确实，这方面怎么说明比较好呢，我感觉挺麻烦的，你有好主意吗 要不我直接兼容两种格式吧，读取配置文件的时候自动删除modid

大佬你看怎么方便实现就怎么来吧，只要标准功能可以生效就行

**Comment by reserveword** [comment]
我试着把tooltip显示的位置翻译了一下，但结果显示的变成i18n的key了（也就是翻译的索引）不知道是不是我翻译的方式不对

**Comment by NightSharp** [comment]
> 我试着把tooltip显示的位置翻译了一下，但结果显示的变成i18n的key了（也就是翻译的索引）不知道是不是我翻译的方式不对 我尽量把名称写得短一点吧

啊，这我就确实搞不懂了，可能是调用方法问题？没搞过开发不太了解，我研究一下翻译条目

**Comment by NightSharp** [comment]
> 我试着把tooltip显示的位置翻译了一下，但结果显示的变成i18n的key了（也就是翻译的索引）不知道是不是我翻译的方式不对 我尽量把名称写得短一点吧

大佬，能不能把你那个显示i18n的key的版本发给我研究一下，我看是不是文本的问题

**Comment by reserveword** [comment]
> 
> 大佬，能不能把你那个显示i18n的key的版本发给我研究一下，我看是不是文本的问题

https://github.com/reserveword/IMBlocker/blob/a95c62311098f66951062a0c530fbdd38a05a606/src/main/java/io/github/reserveword/imblocker/Config.java#L56

tooltip上显示的就是这里的字符串，我试过在这里用`I18n.format`，然后显示的是key，如果你能用什么手段让tooltip显示翻译后的内容，就告诉我一下吧

**Comment by NightSharp** [comment]
> > 大佬，能不能把你那个显示i18n的key的版本发给我研究一下，我看是不是文本的问题
> 
> https://github.com/reserveword/IMBlocker/blob/a95c62311098f66951062a0c530fbdd38a05a606/src/main/java/io/github/reserveword/imblocker/Config.java#L56
> 
> tooltip上显示的就是这里的字符串，我试过在这里用`I18n.format`，然后显示的是key，如果你能用什么手段让tooltip显示翻译后的内容，就告诉我一下吧

3.0.2里是这个版本的代码吗？

**Comment by reserveword** [comment]
> 
> 3.0.2里是这个版本的代码吗？

这个就是从3.0.2里出来的（虽然是对应mc1.16.5的代码），总之找`comment`这个函数就行

**Comment by NightSharp** [comment]
> > 3.0.2里是这个版本的代码吗？
> 
> 这个就是从3.0.2里出来的（虽然是对应mc1.16.5的代码），总之找`comment`这个函数就行

如果先不加`.comment`，然后在lang的json中添加`xxx.comment`项是否可行呢？
另外，我查看过我现在安装的所有模组可用的配置界面，存在汉化的配置界面都是单独编写的，在语言文件中有独立词条，用Configured自动生成的话还没见过可以汉化的

**Comment by reserveword** [comment]
> 
> 如果先不加`.comment`，然后在lang的json中添加`xxx.comment`项是否可行呢？ 另外，我查看过我现在安装的所有模组可用的配置界面，存在汉化的配置界面都是单独编写的，在语言文件中有独立词条，用Configured自动生成的话还没见过可以汉化的

呃，Minecraft的多语言支持是这样的：
1. 首先我们需要在各个语言lang的json文件中定义键值对，比如`"key.imblocker.configstring": "这是一个设置字符串"`，
2. 然后在代码中就可以引用`"key.imblocker.configstring"`，根据mc的语言设置自动选择对应lang文件的字符串。
3. 当然直接把这个key传进各种函数是不行的，需要有一个map进行映射（`I18n.format("key.imblocker.configstring")`就会返回`"这是一个设置字符串"`）

我们现在遇到的问题是，（我猜）在config定义的时候可能`I18n`还没有加载我们的语言文件，就没法成功翻译。

在lang文件中添加单独词条当然是必要的，但是并不会自动塞到config的tooltip里

**Comment by NightSharp** [comment]
> > 如果先不加`.comment`，然后在lang的json中添加`xxx.comment`项是否可行呢？ 另外，我查看过我现在安装的所有模组可用的配置界面，存在汉化的配置界面都是单独编写的，在语言文件中有独立词条，用Configured自动生成的话还没见过可以汉化的
> 
> 呃，Minecraft的多语言支持是这样的：
> 
>     1. 首先我们需要在各个语言lang的json文件中定义键值对，比如`"key.imblocker.configstring": "这是一个设置字符串"`，
> 
>     2. 然后在代码中就可以引用`"key.imblocker.configstring"`，根据mc的语言设置自动选择对应lang文件的字符串。
> 
>     3. 当然直接把这个key传进各种函数是不行的，需要有一个map进行映射（`I18n.format("key.imblocker.configstring")`就会返回`"这是一个设置字符串"`）
> 
> 
> 我们现在遇到的问题是，（我猜）在config定义的时候可能`I18n`还没有加载我们的语言文件，就没法成功翻译。
> 
> 在lang文件中添加单独词条当然是必要的，但是并不会自动塞到config的tooltip里

大佬，如果借用其它的API的话麻烦吗，比如Cloth Config API 什么的，已经在内部实现了配置界面的本地化方法

**Comment by reserveword** [comment]
> 
> 大佬，如果借用其它的API的话麻烦吗，比如Cloth Config API 什么的，已经在内部实现了配置界面的本地化方法

感觉为了这么偏僻的功能加lib不值得。。不过要是你写出来了就不麻烦（笑）

**Comment by NightSharp** [comment]
> > 大佬，如果借用其它的API的话麻烦吗，比如Cloth Config API 什么的，已经在内部实现了配置界面的本地化方法
> 
> 感觉为了这么偏僻的功能加lib不值得。。不过要是你写出来了就不麻烦（笑）

好吧~我只会做点汉化，开发什么的还是算了吧，完全新手233
