### ISSUE TITLE
兼容建议

### ISSUE THREAD

**Issue by OcrSu** [reserveword/IMBlocker#12]
模拟殖民地的建筑命名不可以切换到中文，望修复

**Comment by reserveword** [comment]
使用的Minecraft版本、IMBlocker版本、模拟殖民地版本分别是什么？

**Comment by OcrSu** [comment]
1.16.5 
imblocker-1.16.5-3.0
minecolonies-1.16.5-1.0.709-ALPHA

> 使用的Minecraft版本、IMBlocker版本、模拟殖民地版本分别是什么？

**Comment by reserveword** [comment]
你把`com.ldtteam.blockout.gui.BlockOutScreenGui`这一条加到配置文件的`screenWhitelist`里试试，预期效果应该是在所有模拟殖民地的gui打开时都打开输入法
先试试看能不能用，我再看看怎么修

**Comment by reserveword** [comment]
这模组的代码看得我头大，代码里写着引用了blockout的类，到blockout去找发现根本没有对应的文件，一通搜索发现是旧版本blockout的东西，返回去找引用了哪个版本的blockout发现依赖项里根本没有blockout

**Comment by OcrSu** [comment]
![PFE(O7QU`E_7 ( M9K`0{9P](https://user-images.githubusercontent.com/75876201/167248738-3b3b4f85-5053-4770-8191-f579753b2f12.png)
![3XOD31FB~_NGM(BR@35_66E](https://user-images.githubusercontent.com/75876201/167248744-e3ac01bf-d52f-4454-9b20-6e3edc08e97a.png)


> 你把`com.ldtteam.blockout.gui.BlockOutScreenGui`这一条加到配置文件的`screenWhitelist`里试试，预期效果应该是在所有模拟殖民地的gui打开时都打开输入法 先试试看能不能用，我再看看怎么修

貌似不能用

**Comment by reserveword** [comment]
你装了blockout这个mod吗？如果装了把完整log发给我看看吧
还有就是建议更新一下mod，现在最新版是3.0.1 https://github.com/reserveword/IMBlocker/releases/tag/mc1.16.5-3.0.1

**Comment by reserveword** [comment]
用新版本启动之后如果还不能解决，可以
1. 删掉`com.ldtteam.blockout.gui.BlockOutScreenGui`
2. 把`enableScreenRecovering`改成`true`
3. 重启游戏之后打开重命名的gui
4. 看看`recoveredScreens`项目里的名字
5. 把长得像重命名gui的名字复制到`screenWhitelist`里

**Comment by OcrSu** [comment]
每次往screenWhitelist加入新的名字，启动后都会被重置。。

**Comment by OcrSu** [comment]
我觉得是这个名字 structurize:com.ldtteam.blockout.BOScreen

**Comment by reserveword** [comment]
> 每次往screenWhitelist加入新的名字，启动后都会被重置。。

不应该啊，你更新到3.0.1版本了吗？代码里没有主动修改screenWhitelist的逻辑啊

**Comment by OcrSu** [comment]
已经更新到最新了
![U`4 ISE)42VL8XN0A32MP3F](https://user-images.githubusercontent.com/75876201/167252496-5b468fd7-830e-436c-b4c3-13a32e0a61c1.png)

**Comment by OcrSu** [comment]
> 已经更新到最新了 ![U`4 ISE)42VL8XN0A32MP3F](https://user-images.githubusercontent.com/75876201/167252496-5b468fd7-830e-436c-b4c3-13a32e0a61c1.png)

启动后就变成这样了
![2PH9 `JTT5{M0HC(NOQ8%5E](https://user-images.githubusercontent.com/75876201/167253037-9f381b2e-745f-4141-b79c-76dd527bd2b3.png)

**Comment by reserveword** [comment]
有完整log文件吗？最好是debug版本的

**Comment by OcrSu** [comment]
[debug-1.log](https://github.com/reserveword/IMBlocker/files/8645257/debug-1.log)

**Comment by OcrSu** [comment]
睡觉了，早点休息！

**Comment by reserveword** [comment]
明白了，应该是格式问题，你把`structure:`删掉只留下`com.ldtteam.blockout.BOScreen`应该就好了
我后期应该会更新代码兼容不同格式，你这边先这么试试吧

**Comment by OcrSu** [comment]
FTB任务的窗口也不兼容。
![ZV 309UA$B0C_V6$7~QV5ZK](https://user-images.githubusercontent.com/75876201/167282591-3c7864ec-2142-4b18-b78f-fa9fea2fa616.png)

**Comment by reserveword** [comment]
ftb好像自己实现了一遍输入框，这真的不太容易兼容，建议照样给screen添加白名单
你找到screen名之后告诉我一声，我添加到默认白名单好了

**Comment by OcrSu** [comment]
ftblibrary:dev.ftb.mods.ftblibrary.ui.ScreenWrapper
确认是这个

**Comment by OcrSu** [comment]
目前没有别的发现的不兼容的了，辛苦作者了！

**Comment by reserveword** [comment]
com.ldtteam.blockout.BOScreen已添加到白名单，后续更新会带上
ftblibrary:dev.ftb.mods.ftblibrary.ui.ScreenWrapper这个东西我研究了一下，把ftblib的文本框也考虑进来，不需要额外配置了（也在下次更新里面）

**Comment by OcrSu** [comment]
确认兼容
