### ISSUE TITLE
大佬能否实现按下命令键（'/'）打开的聊天框仍然使用英文？

### ISSUE THREAD

**Issue by qznfbnj** [reserveword/IMBlocker#14]
这个实现会很难吗？如果很难就不需要了

**Comment by reserveword** [comment]
会考虑的（新建文件夹）

**Comment by reserveword** [comment]
下次更新就有了（目前的实现是用`/`打开的聊天框就是英文，如果用`T`或回车打开再输入斜杠不算，睡觉时候的那个也不算）

**Comment by 500kg** [comment]
这个功能能否关闭啊，有很多人习惯用"/"打开输入框

**Comment by reserveword** [comment]
> 这个功能能否关闭啊，有很多人习惯用"/"打开输入框

增加了一个开关的选项，一会发上来
