### ISSUE TITLE
1.20.X新增悬挂告示牌GUI未添加（提供数据希望后续加入）以及抓虫

### ISSUE THREAD

**Issue by Strl3aker** [reserveword/IMBlocker#17]
1实测悬挂告示牌无法自动识别GUI，添加minecraft:net.minecraft.class_7744后可正常使用 希望后续可以直接加入到新版本预设。
2.我查看了添加GUI的那个表单的教程，发现步骤中“只需保存配置后可生效无需重启”这一点存疑，因为本人修改后无法立即生效，重启后生效。（反正我是这样的）
版本IMBlocker-v4.0.1-alpha-mc1.20

**Comment by reserveword** [comment]
1. 感谢提供数据
2. 4.0.2已修复，记得不要在前面加modid和冒号，否则需要重启生效

**Comment by Strl3aker** [comment]
了解，辛苦！
