### ISSUE TITLE
[1.19.2] 服务器中无法正常运行

### ISSUE THREAD

**Issue by fenlincao** [reserveword/IMBlocker#18]
mod版本：1.19.2-3.1.2
forge版本：43.2.6
mod在单人游戏中可以正常运行，但是在加入服务器后却无法正常运行（只有客户端加了此mod），我找不出原因，下面是日志，多谢！
[latest.log](https://github.com/reserveword/IMBlocker/files/11981842/latest.log)

**Comment by fenlincao** [comment]
补充一下，在服务器中有时也可以正常运行，但有时就不行，但是我没有改动任何东西。

**Comment by reserveword** [comment]
> [20:14:10] [Netty Client IO #4/ERROR]: Channels [thirst:main,parcool:message,carryon:carryonpackets,hourglass:channel,timelesspower:timelesspower,sereneseasons:main_channel] rejected vanilla connections

这一行代表客户端和服务器的mod不同步，请检查客户端和服务器mod列表差异，如
`thirst` `parcool` `carryon` `hourglass` `timelesspower` `sereneseasons` 这几个mod

我先关闭issue，如果进一步发现确实是该mod引起的问题你再把issue打开

**Comment by fenlincao** [comment]
多谢，现在基本正常了。
