### ISSUE TITLE
关于移植mod到fabric和更高版本

### ISSUE THREAD

**Issue by bingling-sama** [reserveword/IMBlocker#2]
看到了上一份issues，移植到fabric和更高版本确实是个不错的想法，如果你不介意，我是否可以以此mod为核心理念来制作一个新的fabric mod呢，我会同样发布在GitHub上并使用与您一致的3.0开源协议

**Comment by reserveword** [comment]
快做快做看好你哦（）

**Comment by reserveword** [comment]
https://github.com/reserveword/IMBlocker/issues/1#issuecomment-668398493
https://www.mcbbs.net/thread-1090731-1-1.html
https://github.com/mrjesen/ImBlockerFabric/
已实现
