### ISSUE TITLE
1.20.1 quilt/fabric 游戏崩溃

### ISSUE THREAD

**Issue by 848244210** [reserveword/IMBlocker#21]
你好作者，我下载最新的[IMBlocker]，在1.20.1 quilt/fabric运行，进入服务器的时候发生崩溃。进入任何服务器都会。
请查看HMCL日志。。
[minecraft-exported-crash-info-2023-07-14T00-28-49.zip](https://github.com/reserveword/IMBlocker/files/12041723/minecraft-exported-crash-info-2023-07-14T00-28-49.zip)
[minecraft-exported-crash-info-2023-07-14T00-33-55.zip](https://github.com/reserveword/IMBlocker/files/12041725/minecraft-exported-crash-info-2023-07-14T00-33-55.zip)

**Comment by reserveword** [comment]
本模组未在quilt上测试运行，可能有些问题。日志显示是找不到modmenu里的一个类

**Comment by 848244210** [comment]
> 本模组未在quilt上测试运行，可能有些问题。日志显示是找不到modmenu里的一个类

你好作者，我删除了所有模组测试过也是一样的情况，我也在fabric测试过为一样的情况，我猜测应该不是quilt的问题。

**Comment by 848244210** [comment]
> 本模组未在quilt上测试运行，可能有些问题。日志显示是找不到cloth config里的一个类

另外，根据你的回复，模组是需要cloth 前置嘛，Cloth Config API。我在前置要求好像未找到

**Comment by reserveword** [comment]
> 另外，根据你的回复，模组是需要cloth 前置嘛，Cloth Config API。我在前置要求好像未找到

是的，本模组设计中并不依赖cloth config，不过没有cloth config就没法修改配置了。这里为什么会出问题还需要详细查看

**Comment by reserveword** [comment]
更新：之前推测的原因是错误的，那段报错信息与本模组无关，也不会导致崩溃。
本模组崩溃的原因是有一个地方忘记判断null了，会在接下来的版本中改正
P.S. 仍然建议添加cloth-config模组
