### ISSUE TITLE
最新的4.0.4加载世界时闪退

### ISSUE THREAD

**Issue by Fiocher** [reserveword/IMBlocker#23]
4.0.3-alpha没这个问题，不知道是mod冲突还是啥
[crash-2023-07-21_10.24.27-client.txt](https://github.com/reserveword/IMBlocker/files/12115706/crash-2023-07-21_10.24.27-client.txt)

**Comment by reserveword** [comment]
更新的时候forge有个地方忘记改了，新版本应该能用了
