### ISSUE TITLE
Backport to 1.18.2/1.19.4

### ISSUE THREAD

**Issue by Nukecraft5419** [reserveword/IMBlocker#24]
Hi I'm the CEO of LifeMC Studios we used to use IMBlockerFabric for our modpack now that it seems to be discontinued we would like to know if IMBlocker is a better replacement and if so, if a backport will be coming for 1.18.2 and 1.19.4

**Comment by reserveword** [comment]
我看看，应该没问题

**Comment by Nukecraft5419** [comment]
I hope that support will come for those two versions for now we will do closed tests in 1.20.1 when it comes out for the other two versions we will test it there as well and if it doesn't give any problems we will put it on for the public

**Comment by reserveword** [comment]
> I hope that support will come for those two versions for now we will do closed tests in 1.20.1 when it comes out for the other two versions we will test it there as well and if it doesn't give any problems we will put it on for the public

感谢帮本项目做测试，欢迎多提意见。

**Comment by Nukecraft5419** [comment]
We have noticed a bug that the writing in English is so long that it ends up on the button

![0](https://i.imgur.com/iuFa2zl.png)

**Comment by reserveword** [comment]
1.18.2和1.19.4的向后兼容版本如果没有意外的话应该马上就发布了

**Comment by reserveword** [comment]
> We have noticed a bug that the writing in English is so long that it ends up on the button
> 
英文翻译的功能其实算不得非常重要吧，如果你能帮我想想怎么表达更好我也会非常开心的

**Comment by Nukecraft5419** [comment]
The only way is "text.autoconfig.imblocker.option.useExperimental.line1" and "text.autoconfig.imblocker.option.useExperimental.line2" and the same for "key.imblocker.useExperimental.line1" and "key.imblocker.useExperimental.line2" so as to divide the message into two lines and not make all that mess I can fix the English part and I can also bring the Italian language by making 2 pulls or even others for some improvements to some files and things for now I'll wait until the files are available with the new method so then everything else can be done

**Comment by reserveword** [comment]
> I can also bring the Italian language

意大利语不需要输入法吧？为什么这个mod会需要意大利语翻译？

> divide the message into two lines

我试试看能不能把提示分成两行写

另外，如果可以的话我推荐用中文来交流

**Comment by Nukecraft5419** [comment]
现在我通常使用中文，我的母语是意大利语，但我正在学习英语和日语，也许将来还会学习中文，我已经有这么多语言在学习了，我现在使用 DeepL，希望你能理解。

**Comment by reserveword** [comment]
> 现在我通常使用中文，我的母语是意大利语，但我正在学习英语和日语，也许将来还会学习中文，我已经有这么多语言在学习了，我现在使用 DeepL，希望你能理解。

OK I got it. Welcome for any language translation anyway.

**Comment by Nukecraft5419** [comment]
现在很好，我已经在处理当前的文件了，等分好线后，我会重做的

**Comment by reserveword** [comment]
> 现在很好，我已经在处理当前的文件了，等分好线后，我会重做的

1.18.2 and 1.19.4 version is now （alpha）published on github/modrinth/curseforge.

**Comment by reserveword** [comment]
> 我们在 LifeMC 工作室团队中进行了一些测试，结果发现在 1.18.2 和 1.19.4 中，我们必须通过 fabric_loader_dependencies.json 强制使用 IMBlocker。

I'm confused, I throught a mod is automatically enabled once placed in `.minecraft/mods` or somewhere like that.

Are you saying it isn't identified as a mod so we must mark it as someone else's dependency to load it?

**Comment by Nukecraft5419** [comment]
No, but usually that file is also used to force the mod to run in versions other than the one it was designed for Check here for both 1.18.2 and 1.19.4 https://github.com/LifeMC-Studios/LifeMC/blob/main/Packwiz/1.18.2/config/fabric_loader_dependencies.json

**Comment by reserveword** [comment]
> No, but usually that file is also used to force the mod to run in versions other than the one it was designed for Check here for both 1.18.2 and 1.19.4 https://github.com/LifeMC-Studios/LifeMC/blob/main/Packwiz/1.18.2/config/fabric_loader_dependencies.json

will fix it in next version

**Comment by reserveword** [comment]
fixed

**Comment by reserveword** [comment]
feel free to open another issue if you find anything else
