### ISSUE TITLE
1.16.5最新版本 打开某个输入框然后esc手动关闭输入法  mod的作用才能起效

### ISSUE THREAD

**Issue by Linwendong83** [reserveword/IMBlocker#25]
如题 每次进入游戏都需要进行这样的操作，不进行这样的操作相当于未安装mod

**Comment by reserveword** [comment]
这个bug在新版本应该已经修了，我把新版本移植过来你看看能不能用吧

**Comment by reserveword** [comment]
> 这个bug在新版本应该已经修了，我把新版本移植过来你看看能不能用吧

我又看了一下，新版本好像没法直接套用到1.16.5上，只能在之前的基础上加上修bug的代码吧

**Comment by reserveword** [comment]
更新了，因为各种原因版本号只是3.1.2+patch4.0.5，试试看吧

**Comment by Linwendong83** [comment]
非常感谢

**Comment by Linwendong83** [comment]
在非全屏模式下启动游戏仍旧有此问题
