### ISSUE TITLE
1.16.5最新版本 在非全屏模式下启动游戏 打开某个输入框然后esc手动关闭输入法 mod的作用才能起效

### ISSUE THREAD

**Issue by Linwendong83** [reserveword/IMBlocker#26]
如题

**Comment by reserveword** [comment]
请确认你的版本是不是7月23日发布的那个版本，这个问题应该在那个版本修复了啊

**Comment by Linwendong83** [comment]
> 请确认你的版本是不是7月23日发布的那个版本，这个问题应该在那个版本修复了啊

是的 但是还是会触发这个问题 只要在开启游戏时不打开全屏 以及能否加入对按/键的识别 以及有一定概率输入大量错误字符（1.20.1最新版本） 比如输入shuru 还没有选择输入法上的某一项 就会打出ssssshhhurrrrrruuuu类似的东西

**Comment by reserveword** [comment]
我想想怎么修这个吧，实在不行就加载完成之后延时刷新一下状态

**Comment by Linwendong83** [comment]
> 我想想怎么修这个吧，实在不行就加载完成之后延时刷新一下状态

能否加入对/键的识别 现在私聊/w或者/tell非常反人类 以及我提到的ssssshhhurrrrrruuuu的问题

**Comment by reserveword** [comment]
> 能否加入对/键的识别 现在私聊/w或者/tell非常反人类 以及我提到的ssssshhhurrrrrruuuu的问题 把这这些问题修了这个mod就完美了 现在有时候感觉还不如win+空格切换

斜杠输入命令应该已经识别了啊，有一个开关可以控制斜杠输入命令是否开启输入法，默认是不开启的（因为命令一般不用写中文）

我这几天应该会把这个问题修起来了

**Comment by reserveword** [comment]
我又测试了一下，无法复现这一问题。如果又遇到同样问题的人请重新打开这个issue。
