### ISSUE TITLE
Curseforge上的信息错误

### ISSUE THREAD

**Issue by HhiPyrene** [reserveword/IMBlocker#29]
如图，Curseforge上该模组支持的MC版本与模组加载器信息缺失或错误，对模组的更新带来了一定程度上的不便
![wrong](https://github.com/reserveword/IMBlocker/assets/111572269/d7ef2ed0-9fc3-4f37-9ace-e40de97efa5a)

**Comment by reserveword** [comment]
现存发布已修改，未来如何避免还没确定

**Comment by reserveword** [comment]
fixed
