### ISSUE TITLE
模组导致 Voxel Map Updated 世界地图的右键菜单无法使用

### ISSUE THREAD

**Issue by MaoYan5985** [reserveword/IMBlocker#31]
![7](https://github.com/reserveword/IMBlocker/assets/122714639/7c1f2784-d923-4506-a906-4eb863259ac5)

安装Imblocker后，Voxel Map Updated 世界地图的右键菜单无法使用，右键后会导致菜单一闪而过，然后消失。

- MC：1.20.1
- Fabric：0.14.22
- IMBlocker_4.0.5+1.20
- voxelmap-1.20.1-1.12.13

**Comment by Fiz-Victor** [comment]
在设置里面可以关闭实验性选项应该可以解决

**Comment by reserveword** [comment]
fixed
