### ISSUE TITLE
1.20.2兼容

### ISSUE THREAD

**Issue by charassss** [reserveword/IMBlocker#33]
两个电脑测试1.20的4.0.5和4.0.8,均无法正常使用

**Comment by AstroAbyss** [comment]
麻烦跟进Minecraft 1.20.2的模组更新。
Please follow up on the mod update for Minecraft 1.20.2.

**Comment by LrbsX** [comment]
麻烦跟进Minecraft 1.20.2的模组更新。+1
Please follow up on the mod update for Minecraft 1.20.2. +1

**Comment by reserveword** [comment]
已更新1.20.4
