### ISSUE TITLE
疑似不兼容macos

### ISSUE THREAD

**Issue by Wudji** [reserveword/IMBlocker#35]
根据https://github.com/Wudji/XPlus-2.0-Modpack/issues/6 提供的信息，该模组似乎不兼容macos。

因为wudji现在在上高三，没有条件验证这个问题是否在最新版本中仍存在，辛苦作者看一下了～

**Comment by bowling233** [comment]
显然是不兼容的，我在 macOS 上用 XPlus 也出现这个情况。查看日志是因为 IMBlock 调用了 Windows SDK 的 `imm32.lib` 而 macOS 上显然不会有也无法安装。README 中也说了非 Windows 环境下暂时没有找到控制输入法的方法。建议非 Windows 系统使用时在整合包中关闭该 MOD。

**Comment by Wudji** [comment]
如果做不了兼容的话能不能在检测到环境为macos时禁用此模组？
