### ISSUE TITLE
无法兼容小狼毫输入法

### ISSUE THREAD

**Issue by qwd145-zhi** [reserveword/IMBlocker#40]
在1.20中试图使用小狼毫输入法发现失败，仅能输入英文。

**Comment by reserveword** [comment]
按理说这个mod不会干预输入法自身的实现啊，有试过切到别的输入法吗？是只有这个输入法无法正常使用吗？

**Comment by reserveword** [comment]
可以进一步提供一些信息吗？

**Comment by qwd145-zhi** [comment]
不好意思现在才看到消息。我当时有尝试过其他的输入法，就只有这个输入法无法使用。有趣的是，我当时尝试了当时我能够找到的相关模组，均无法使用该输入法。

**Comment by reserveword** [comment]
> 不好意思现在才看到消息。我当时有尝试过其他的输入法，就只有这个输入法无法使用。有趣的是，我当时尝试了当时我能够找到的相关模组，均无法使用该输入法。

那有可能是输入法自身的问题吧，如果没装本mod也无法使用小狼毫输入法的话我们也无能为力

**Comment by qwd145-zhi** [comment]
那不好意思 给你们添麻烦了qwq
