### ISSUE TITLE
[Bug] 运行在 Linux  Deepin 20.9 上边，哪怕只有 IMB 这个 mod，也崩溃

### ISSUE THREAD

**Issue by 8MiYile** [reserveword/IMBlocker#44]
[minecraft-exported-crash-info-2024-04-06T19-01-26.zip](https://github.com/reserveword/IMBlocker/files/14893312/minecraft-exported-crash-info-2024-04-06T19-01-26.zip)

**Comment by reserveword** [comment]
Linux现在不受支持，相关讨论请见#6
