### ISSUE TITLE
Modrinth 和 CurseForge 的支持版本标注错误

### ISSUE THREAD

**Issue by NyteWL** [reserveword/IMBlocker#48]
如图
![image](https://github.com/reserveword/IMBlocker/assets/163705449/c25441e6-d4c4-4804-ac3c-830c2e021778)
![image](https://github.com/reserveword/IMBlocker/assets/163705449/9b6ae78e-a3c1-4285-aae8-6ad57a065ac8)

**Comment by reserveword** [comment]
等我下周改过来吧QAQ
