### ISSUE TITLE
安装之后无法在jei搜索框切换输入法

### ISSUE THREAD

**Issue by Death-123** [reserveword/IMBlocker#5]

**Comment by reserveword** [comment]
暂时建议使用[jech拼音搜索](https://www.mcmod.cn/class/840.html)，其实我觉得拼音搜索大部分时候比打字方便（但我还是会尽力修的）

**Comment by Death-123** [comment]
其实是1.16的jech没支持拼音搜索tooltips(就是搜fengli搜不出锋利附魔书,汉字锋利可以搜到),我已经给jech发了issue了(

**Comment by reserveword** [comment]
[1.16.5 版本](https://github.com/reserveword/IMBlocker/releases/tag/mc1.16.5-2.0)已修复
