### ISSUE TITLE
MC 1.20.1 macbook 崩溃

### ISSUE THREAD

**Issue by maclaylq** [reserveword/IMBlocker#53]
我用的是mac系统，使用此mod崩溃，我要跟windows的联机。可否上个mc 1.20.1版本的修复版本。我看最近有修改这个问题。

**Comment by reserveword** [comment]
本mod是纯客户端mod，删除mod不影响联机游戏。我没有mac环境，不方便测试这方面功能，或许会考虑将修复添加到1.20.1，不过不保证

**Comment by maclaylq** [comment]
就是为了可以使用这个mod，两个笔记本联机问题。我自己编译了个版本。还是感谢。
