### ISSUE TITLE
1.21始终崩溃

### ISSUE THREAD

**Issue by Sczr0** [reserveword/IMBlocker#54]
[错误报告-2024-8-20_14.35.54.zip](https://github.com/user-attachments/files/16670221/-2024-8-20_14.35.54.zip)
如标题

**Comment by reserveword** [comment]
能确定是本mod的问题吗？请提供完整的错误报告，附件里的日志并不包含使程序崩溃的错误，无法判断崩溃的原因。

**Comment by Sczr0** [comment]
> 能确定是本mod的问题吗？请提供完整的错误报告，附件里的日志并不包含使程序崩溃的错误，无法判断崩溃的原因。

事实上，即使我卸载了该mod游戏依然反复崩溃，我更新了显卡驱动并经过了三个小时的简单测试，目前没有再出现过崩溃现象
目前我正在把该mod重新安装回游戏测试，排查是不是mod的问题
之所以之前怀疑是mod的问题，是因为加上mod了之后游戏显然更容易崩溃，并且我简单看了一下日志，并把日志给ai分析了之后发现可能是这个mod的问题
关于日志，这是pcl导出来的错误报告，我不知道该从哪里寻找更多的信息
