### ISSUE TITLE
你好，该mod能否更新1.21.1版本？

### ISSUE THREAD

**Issue by bidgeQwQ** [reserveword/IMBlocker#55]
你好，该mod能否更新1.21.1版本？

**Comment by reserveword** [comment]
不是有了吗
https://github.com/reserveword/IMBlocker/releases/tag/v4.0.9b%2B1.21

**Comment by Blalala6868** [comment]
> 不是有了吗 https://github.com/reserveword/IMBlocker/releases/tag/v4.0.9b%2B1.21

那可不可以注明一下这玩意支持1.21.1，不然很容易让人认为这不兼容

**Comment by reserveword** [comment]
> 那可不可以注明一下这玩意支持1.21.1，不然很容易让人认为这不兼容

抱歉我没注意要的是1.21.1，不过小版本如果没有发现不兼容的话都是默认兼容的，不会出新版本。如果发现不兼容的情况请说明。
