### ISSUE TITLE
会导致FTB任务的任务描述界面无法输入中文。

### ISSUE THREAD

**Issue by 7yudinglaopin8** [reserveword/IMBlocker#58]
会导致FTB任务的任务描述界面无法输入中文，因为FTB任务的任务描述GUI在IMblocker里会默认禁用掉输入法。
应该是启用输入法才对。

**Comment by reserveword** [comment]
https://github.com/reserveword/IMBlocker/issues/13
是否尝试过给gui屏幕添加白名单？

**Comment by 7yudinglaopin8** [comment]
> #13 是否尝试过给gui屏幕添加白名单？

不是，你只需要告诉我白名单里输入啥，我不知道输入什么才能让FTB的GUI屏幕添加到白名单，谢谢。

**Comment by reserveword** [comment]
https://github.com/reserveword/IMBlocker/issues/13#issuecomment-2261790887
`ftblibrary:dev.ftb.mods.ftblibrary.ui.ScreenWrapper`
可以参考这个

**Comment by 7yudinglaopin8** [comment]
> [#13 (comment)](https://github.com/reserveword/IMBlocker/issues/13#issuecomment-2261790887) `ftblibrary:dev.ftb.mods.ftblibrary.ui.ScreenWrapper` 可以参考这个

谢谢啦。
