### ISSUE TITLE
疑似imblocker导致游戏崩溃

### ISSUE THREAD

**Issue by lgc2333** [reserveword/IMBlocker#8]
[错误报告-2022-1-28_0.19.47.zip](https://github.com/reserveword/IMBlocker/files/7952052/-2022-1-28_0.19.47.zip)

**Comment by reserveword** [comment]
那啥，你这个mod不是我写的啊，是这位（应该吧）[https://github.com/lss233/InputMethodBlocker](https://github.com/lss233/InputMethodBlocker)

**Comment by lgc2333** [comment]
不好意思qwq

从 Windows 版邮件发送

发件人: reserveword
发送时间: 2022年1月28日 1:25
收件人: reserveword/IMBlocker
抄送: student_2333; Author
主题: Re: [reserveword/IMBlocker] 疑似imblocker导致游戏崩溃 (Issue #8)

那啥，你这个mod不是我写的啊，是这位（应该吧）https://github.com/lss233/InputMethodBlocker
